### ISSUE TITLE
版权相关问题

### ISSUE THREAD

**Issue by cnweibo** [li-xinyang/FEND_Note#37]
作者很不厚道，你的这种分享精神值得赞赏，但是应该尊重网易云课堂的辛勤付出，至少应该注明出处，说一下是来自于网易云课堂前端微专业的学习笔记。尊重原创，从我做起。我们都是知识工作者，如果自己都不尊重知识产权，何来发展？！

**Comment by li-xinyang** [comment]
感谢您的提醒。我以标注出内容及大纲出处。在发布前已将部分图片重绘及重新编写示例所有的代码。如有侵权，请告知。我会将其删除。

**Comment by li-xinyang** [comment]
关闭主题，如果有任何异议和需要讨论支持可随时重新开启本主题。
